### ISSUE TITLE
TTLRUCache.AddWithExpire and AddWithTTL are fundamentally broken.

### ISSUE THREAD

**Issue by jvmatl** [robmccoll/mitlru#1]
Hi! Generally, thanks for this library, it has been very useful at work. ;)

I happened to be code reviewing some places where the cache is used and I got sidetracked looking over the implementation of the cache itself - that's when I noticed that the AddWith{Expire,TTL} functions appear to be broken by design. As long as everything in the queue uses the default TTL, everything is fine. (Fortunately, this is how we use it, and this is the only case that is covered in the unittests) 

But when the TTLs vary, expiration does not work as expected, because it does a linear search of the timeorder queue from front to back, under the assumption that the last item added to the queue should be the last item to expire.

Consider the following test:

```go
func TestTimeOrdering(t *testing.T) {
	lru := NewTTLRUCache(5, 3*time.Second)

	lru.Add("key0", "valid for 3 seconds")
	lru.Add("key1", "valid for 3 seconds")
	lru.AddWithTTL("key2", "valid for 1 second", 1*time.Second)

	time.Sleep(2 * time.Second)

	if _, b := lru.Get("key2"); b {
		t.Error("Should not contain key2")
	}
}
```

All the 'fixes' I can think of would involve a significant drop in big-O performance, so my recommendation (assuming you want to keep those APIs) would be to fork the implementation into two types: one cache that *only* uses the default TTL for expiration but preserves the linear near-constant-time add, and another that allows variable TTLs, but relies on a Heap structure to maintain a valid time ordering..

**Comment by robmccoll** [comment]
Thanks! Opted for correctness with poor performance in the general case.
